# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Go install and cache"
description: "Install and cache a go package"
author: "tcodes0"
inputs:
  package:
    description: "Go package to install"
    required: true
runs:
  using: "node20"
  main: "dist/action/index.js"
  post: "dist/post/index.js"
branding:
  icon: "download-cloud"
  color: "gray-dark"
